services:
  frontend:
    build: ./frontend
    image: ishikii/docx_front:refactor
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    image: ishikii/docx_backend:refactor
    ports:
      - "3000:3000"
